FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY requirements_db.txt .
RUN pip install --no-cache-dir -r requirements_db.txt

# Copy the database handler script
COPY database_handler.py .

CMD ["python", "database_handler.py"]
